"""Structured inputs and outputs for the procedure-generation agent."""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class AgentBaseModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_assignment=True,
    )


class ContextDocument(AgentBaseModel):
    id: str
    name: str
    direction: str


class ContextNote(AgentBaseModel):
    id: str
    text: str


class ContextNeighbour(AgentBaseModel):
    id: str
    name: str
    actor_name: str | None = None
    element_kind: str


class ContextBranch(AgentBaseModel):
    gateway_id: str
    gateway_name: str | None = None
    label: str | None = None
    condition: str | None = None
    is_default: bool = False
    target_element_id: str
    target_name: str | None = None


class OperationContext(AgentBaseModel):
    operation_number: int
    bpmn_element_id: str
    raw_name: str
    actor_name: str | None = None
    element_kind: str
    source_type: str

    previous_operations: list[ContextNeighbour] = Field(
        default_factory=list
    )
    next_operations: list[ContextNeighbour] = Field(
        default_factory=list
    )

    input_documents: list[ContextDocument] = Field(
        default_factory=list
    )
    output_documents: list[ContextDocument] = Field(
        default_factory=list
    )

    notes: list[ContextNote] = Field(default_factory=list)
    branches: list[ContextBranch] = Field(default_factory=list)

    order_ambiguous: bool = False
    validation_issue_codes: list[str] = Field(
        default_factory=list
    )


class GeneratedOperationContent(AgentBaseModel):
    """Content generated by the LLM for one trusted operation context."""

    description: str = Field(min_length=1)

    incorporated_note_ids: list[str] = Field(
        default_factory=list
    )

    confidence: float = Field(
        ge=0.0,
        le=1.0,
    )

    requires_validation: bool = False

    warnings: list[str] = Field(
        default_factory=list
    )


class OperationDraft(AgentBaseModel):
    operation_number: int
    bpmn_element_id: str

    description: str

    input_document_names: list[str] = Field(
        default_factory=list
    )
    output_document_names: list[str] = Field(
        default_factory=list
    )

    incorporated_note_ids: list[str] = Field(
        default_factory=list
    )

    confidence: float = Field(ge=0.0, le=1.0)
    requires_validation: bool = False
    warnings: list[str] = Field(default_factory=list)


class ProcedureDraft(AgentBaseModel):
    process_id: str
    title: str
    operations: list[OperationDraft] = Field(
        default_factory=list
    )

    generation_warnings: list[str] = Field(
        default_factory=list
    )

    @property
    def operation_count(self) -> int:
        return len(self.operations)

    def operation_by_id(
        self,
        bpmn_element_id: str,
    ) -> OperationDraft | None:
        return next(
            (
                operation
                for operation in self.operations
                if operation.bpmn_element_id
                == bpmn_element_id
            ),
            None,
        )
