"""Models used by the specification narrative pipeline."""

from __future__ import annotations

import re
import unicodedata

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
    model_validator,
)


class NarrativeBaseModel(BaseModel):
    """Shared configuration for narrative models."""

    model_config = ConfigDict(
        extra="forbid",
        validate_assignment=True,
    )


class NarrativeBranch(NarrativeBaseModel):
    """One decision branch exposed to narrative generation."""

    gateway_name: str | None = None
    label: str
    condition: str | None = None
    is_default: bool = False

    target_operation_number: int | None = None
    target_operation_name: str

    is_loop_back: bool = False


class NarrativeOperation(NarrativeBaseModel):
    """One deterministic process element exposed to the narrative LLM."""

    number: int
    bpmn_element_id: str | None = None

    actor: str | None = None
    lane_context: str | None = None

    raw_name: str
    description: str | None = None

    element_kind: str
    source_type: str | None = None

    execution_mode: str
    event_role: str | None = None

    previous_operation_numbers: list[int] = Field(default_factory=list)
    next_operation_numbers: list[int] = Field(default_factory=list)
    loop_target_operation_numbers: list[int] = Field(default_factory=list)

    is_divergence: bool = False
    is_convergence: bool = False

    branches: list[NarrativeBranch] = Field(default_factory=list)
    business_rules: list[str] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)
    input_documents: list[str] = Field(default_factory=list)
    output_documents: list[str] = Field(default_factory=list)


class NarrativeContext(NarrativeBaseModel):
    """Deterministic process context sent to narrative generation."""

    process_id: str
    process_title: str
    end_event_status: str = "unknown"
    actors: list[str] = Field(default_factory=list)
    operations: list[NarrativeOperation] = Field(default_factory=list)
    documents: list[str] = Field(default_factory=list)
    business_rules: list[str] = Field(default_factory=list)


class GeneratedNarrativeQualitySummary(NarrativeBaseModel):
    paragraph_count: int = Field(ge=1)
    placeholder_count: int = Field(default=0, ge=0)
    max_paragraph_characters: int = Field(ge=1)


_PLACEHOLDER_PATTERNS = (
    "texte à générer",
    "texte a generer",
    "à compléter",
    "a completer",
    "todo",
    "placeholder",
)


def _normalize_for_matching(text: str) -> str:
    normalized = unicodedata.normalize("NFKD", text)
    normalized = "".join(
        character
        for character in normalized
        if not unicodedata.combining(character)
    )
    normalized = normalized.casefold()
    normalized = re.sub(r"[^a-z0-9]+", " ", normalized)
    return " ".join(normalized.split())


def _contains_placeholder(text: str) -> bool:
    normalized = _normalize_for_matching(text)
    return any(
        _normalize_for_matching(pattern) in normalized
        for pattern in _PLACEHOLDER_PATTERNS
    )


class GeneratedNarrative(NarrativeBaseModel):
    """Multi-paragraph narrative generated by Qwen.

    The optional model and quality fields are part of the current Kaggle
    contract.  They remain optional so previously generated narratives can
    still be loaded.
    """

    process_id: str = Field(min_length=1)
    process_title: str = Field(min_length=1)
    model_name: str | None = None
    paragraphs: list[str] = Field(min_length=1)
    quality_summary: GeneratedNarrativeQualitySummary | None = None

    @field_validator("paragraphs")
    @classmethod
    def clean_paragraphs(cls, paragraphs: list[str]) -> list[str]:
        cleaned = [
            " ".join(paragraph.split()).strip()
            for paragraph in paragraphs
        ]
        if any(not paragraph for paragraph in cleaned):
            raise ValueError("Narrative paragraphs must not be empty.")
        return cleaned

    @model_validator(mode="after")
    def validate_quality_summary(self) -> "GeneratedNarrative":
        actual_placeholder_count = sum(
            _contains_placeholder(paragraph)
            for paragraph in self.paragraphs
        )

        if self.quality_summary is not None:
            if self.quality_summary.paragraph_count != len(self.paragraphs):
                raise ValueError(
                    "quality_summary.paragraph_count does not match paragraphs."
                )

            actual_max = max(len(paragraph) for paragraph in self.paragraphs)
            if self.quality_summary.max_paragraph_characters != actual_max:
                raise ValueError(
                    "quality_summary.max_paragraph_characters does not match "
                    "the narrative paragraphs."
                )

            if self.quality_summary.placeholder_count != actual_placeholder_count:
                raise ValueError(
                    "quality_summary.placeholder_count does not match "
                    "the narrative content."
                )

        return self

    @property
    def placeholder_count(self) -> int:
        if self.quality_summary is not None:
            return self.quality_summary.placeholder_count
        return sum(
            _contains_placeholder(paragraph)
            for paragraph in self.paragraphs
        )
